name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn
      - name: Lint
        id: lint
        run: yarn lint:nofix

      - name: Unit Test
        id: unit-test
        run: yarn test:unit

  release:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install
      - name: Build artifacts
        id: build
        run: yarn package

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'alerta-webui.zip,tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          allowUpdates: true
